# Generated by Django 3.0.7 on 2021-01-22 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_auto_20201222_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='time off start date')),
                ('date_end', models.DateField(verbose_name='time off start date')),
                ('approved', models.BooleanField(default=False, verbose_name='approved')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_requests', to='people.Employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'Time Off Request',
                'verbose_name_plural': 'Time Off Requests',
            },
        ),
    ]
