# Generated by Django 3.0.7 on 2021-04-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_timeoffrequest'),
        ('people', '0025_auto_20210210_1529'),
    ]

    operations = [
    ]
